### ISSUE TITLE
Isn't ready yet

### ISSUE THREAD

**Issue by Herb0yk** [lilydjwg/bookmarked-search#2]
It offers defacto only one out of sixteen of my search engines, but instead a google search which I don't have in my engines and some strange stuff like: j (statement), ja (expression), etc.

I think it needs a rework however the function as promised is what I'm waiting for. The other alternatives around have other lacks of usability.

**Comment by lilydjwg** [comment]
Can you try out 0.2.2? I've just released this new version.

**Comment by lilydjwg** [comment]
To be clear, this addon finds only your bookmarks with `%s` in the url, not your normal search engines (and not those search with a POST request).

**Comment by Herb0yk** [comment]
It doesn't make any difference, it displays the same.
Concerning your clarification, I have no clue how to know these details.

**Comment by lilydjwg** [comment]
Did you add your bookmark for search like this?

![add a keyword bookmark](https://addons.cdn.mozilla.net/user-media/previews/full/187/187593.png)
