### ISSUE TITLE
点了“书签搜索”没反应

### ISSUE THREAD

**Issue by ghost** [lilydjwg/bookmarked-search#3]
操作步骤如下
![image 001](https://user-images.githubusercontent.com/31858966/30285426-a8120d4e-9750-11e7-8165-2d08e5d2d994.png)
![image 002](https://user-images.githubusercontent.com/31858966/30285435-b02eed26-9750-11e7-8121-4aef9f10adff.png)
点下去没反应
![image 003](https://user-images.githubusercontent.com/31858966/30285425-a6d773f6-9750-11e7-856c-46add15672d4.png)

**Comment by lilydjwg** [comment]
你的操作过程没有问题。你可以按以下步骤获取调试信息吗？

打开 about:debugging 页面，启用附加组件调试，然后找到「书签搜索」，点它下方的「调试」。在弹出的控制台窗口中，先点一下左上角的垃圾桶图标清除一下，然后在下方输入「LOGGING = true」并回车。再回到网页上使用书签搜索菜单，看看控制台窗口中是不是有报错。

**Comment by ghost** [comment]
![image 1](https://user-images.githubusercontent.com/31858966/30312722-528b3404-97cd-11e7-84a6-62bf60cde74e.png)

**Comment by ghost** [comment]
顺便说一下，我用的火狐55.0.3（64位）

**Comment by lilydjwg** [comment]
好的，原来这个东西是 57 才支持的： https://bugzilla.mozilla.org/show_bug.cgi?id=1238314

我修改一下，去掉这个试试。

**Comment by ghost** [comment]
看来修复了，坐等上架

**Comment by lilydjwg** [comment]
已经上架，你再试试看？

**Comment by ghost** [comment]
能用了，这个issue可以关掉了
