### ISSUE TITLE
Open search tab in foreground by default?

### ISSUE THREAD

**Issue by I60R** [lilydjwg/bookmarked-search#4]
I've noticed that I press `Ctrl+Tab` most times after I've selected "Search with" in context menu.  
Does it make sense to always open search tab in foreground?
I.e. "Search Google for %S" menu entry have the same behavior.

**Comment by lilydjwg** [comment]
Actually I hate opening in foreground because I'll have to wait for it to load, and I want to finish reading the whole paragraph then turn to the search result.

But your use case is reasonable too. I may make it an option in the future.

**Comment by I60R** [comment]
Okay I understand. 
Probably implementing that option could be a waste of time, because I found another extension with behavior I want and that issue can be closed. 

Thank you for feedback and useful add-on

**Comment by lilydjwg** [comment]
In version 3.0 I've made it the same as the new `Search xxx` menu item: use Ctrl+left click or middle click to open in background, otherwise in foreground.
